name: dockerhub

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tags:
        description: "Dockerhub tags"
        required: false
        default: ""

jobs:
  cache_layers:
    name: Cache Docker image parts
    uses: ./.github/workflows/docker_reusable.yml
    with:
      caching_layers: true

  push_to_registry:
    needs:
      - cache_layers
    name: Push Docker image to Docker Hub
    uses: ./.github/workflows/docker_reusable.yml
    with:
      pushing: true